pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from Git
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Use withEnv to set the PATH variable
                withEnv(["PATH+NODEJS=${tool 'Node.js'}/bin:$PATH"]) {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                // Run the npm build script
                sh 'npm run build'
            }
        }
    }
}
