pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from Git
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Use withEnv to set the PATH variable
                withEnv(["PATH+NODEJS=${tool 'Node.js'}/bin:$PATH"]) {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                // Use withEnv to set the PATH variable
                withEnv(["PATH+NODEJS=${tool 'Node.js'}/bin:$PATH"]) {
                    sh 'npm run build'
                }
            }
        }

        stage('Upload Artifacts to S3') {
            steps {
                script {
                    def awsS3Bucket = 'myartifacts-jenkins-emon'
                    def buildFolder = 'dist'
                    
                    // Use the AWS CLI to upload artifacts
                    sh "aws s3 sync $buildFolder s3://$awsS3Bucket/"
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts 'dist/**'
        }
    }
}
